FORMAT: 1A
HOST: http://www.interswellar.me/api/v1/

# Interswellar API

Interswellar API is a simple API allowing users to query the Interswellar Database.

### List Stars [GET /stars]

+ Response 200 (application/json)

        [
            {
                "name": "Kepler-9"
                "mass": 1.07,
                "luminosity": 13.9,
                "temperature": 5777.00,
                "radius": 1.02,
                "constellation": "Lyra",
                "planets": [ "Kepler-9a", "Kepler-9b", "Kepler-9d" ]
                "discovered_by": "http://adsabs.harvard.edu/abs/2013A%26A...556A.126A"
            },
            {
                "name": "HIP 64690"
                "mass": 0.95,
                "luminosity": 0.810,
                "temperature": 5679.00,
                "radius": 0.93,
                "constellation": "Octans"
                "planets": []
                "discovered_by": "http://adsabs.harvard.edu/abs/2011A%26A...534A..58P"
            },
            ...
        ]
        
### Find Star [GET /star/{name}]

+ Parameters
    + name (required, string, `HIP 64690`) ... Star Name

+ Response 200 (application/json)

        {
            "name": "HIP 64690"
            "mass": 0.95,
            "luminosity": 0.810,
            "temperature": 5679.00,
            "radius": 0.93,
            "constellation": "Lyra",
            "planets": [ "Kepler-9a", "Kepler-9b", "Kepler-9d" ]
            
            "discovered_by": "http://adsabs.harvard.edu/abs/2011A%26A...534A..58P"
        }


### List Exoplanets [GET /exoplanets]

+ Response 200 (application/json)

        [
            {
                "name": "HD 49674 b"
                "mass": 33.40000,
                "radius": "unknown",
                "orbital_period": 2451883.700000,
                "discovery_year": 2002,
                "star": "HD 49674",
                "constellation": "Auriga",
                "discovered_by": "http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=2003ApJ...582..455B"
            },
            {
                "name": "Kepler-24 b"
                "mass": 33.30000,
                "radius": 2.020,
                "orbital_period": "unknown"
                "discovery_year": 2011,
                "star": "Kepler-24"
                "constellation": "Lyra"
                "discovered_by": "http://adsabs.harvard.edu/abs/2014ApJ...787...80H"
            },
            ...
        ]

### Find Exoplanet [GET /exoplanet/{name}]

+ Parameters
    + name (required, string, `Kepler-24 b`) ... Exoplanet Name

+ Response 200 (application/json)

        {
            "name": "Kepler-24 b"
            "mass": 33.30000,
            "radius": 2.020,
            "orbital_period": "unknown",
            "discovery_year": 2011,
            "star": "Kepler-24",
            "constellation": "Lyra",
            "discovered_by": "http://adsabs.harvard.edu/abs/2014ApJ...787...80H"
        }


### Find Constellation [GET /constellation/{name}]

+ Parameters
    + name (required, string, `Lyra`) ... Constellation Name

+ Response 200 (application/json)

        {
            "name": "Lyra"
            "IAU_abbreviation": "Lyr",
            "family": "Hercules",
            "meaning": "lyre / harp",
            "area": 286,
            "bordering_constellation": ["Draco", "Hercules", "Vulpecula", "Cygnus"],
            "stars": ["Kepler-24", "Kepler-9", ...]
        }


### Find Publication [GET /publication/{ref}]

+ Parameters
    + ref (required, string, `2013A&A...556A.126A`) ... Publication Reference

+ Response 200 (application/json)

        {
            "name": "A dynamically-packed planetary system around GJ 667C with three super-Earths in its habitable zone"
            "year": "2013",
            "authors": ["Anglada-Escudé, Guillem","Tuomi, Mikko","Gerlach, Enrico","Barnes, Rory", ...],
            "journal": "Astronomy & Astrophysics",
            "abstract": "Context. Since low-mass stars have low luminosities, orbits...",
            "stars_discovered": ["HD 285968", "HD 40307", "HD 69830", ...],
            "planets_discovered": ["GJ 581 d", "GJ 1214 b", ...]
        }