FORMAT: 1A
HOST: http://www.interswellar.me/api/v1/

# Interswellar API

Interswellar API is a simple API allowing users to query the Interswellar Database.

## Stars [/stars]

### List Stars [GET /stars?page={n}]

+ Parameters
    + n (optional, integer, `1`) ... Page Number

+ Response 200 (application/json)

        {
            "num_results": 2, 
            "objects": [
                {
                    "id": 1, 
                    "name": "Kepler-9", 
                    "luminosity": 13.9, 
                    "mass": 1.07, 
                    "radius": 1.02, 
                    "temperature": 5777.00,
                    "constellation": {"id": 1, "abbrev": "Lyr"}, 
                    "exoplanets": [
                        {"id": 1, "name": "Kepler-9a"},
                        {"id": 2, "name": "Kepler-9b"},
                        {"id": 3, "name": "Kepler-9d"}
                    ],
                    "discoverer": {"id": 1, "ref": "2013A&A...566A.126A"}
                },
                {
                    "id": 2, 
                    "name": "HIP 64690", 
                    "luminosity": 0.810, 
                    "mass": 0.95, 
                    "radius": 0.93, 
                    "temperature": 5679.00,
                    "constellation": {"id": 1, "abbrev": "Oct"}, 
                    "exoplanets": [],
                    "discoverer": {"id": 1, "ref": "2011A&A...534A..58P"}
                }
            ], 
            "page": 1, 
            "total_pages": 1
        }

        
### Find Star [GET /stars/{id}]

+ Parameters
    + id (required, integer, `1`) ... Star ID

+ Response 200 (application/json)

        {
            "id": 1, 
            "name": "Kepler-9", 
            "luminosity": 13.9, 
            "mass": 1.07, 
            "radius": 1.02, 
            "temperature": 5777.00,
            "constellation": {"id": 1, "abbrev": "Lyr"}, 
            "exoplanets": [
                {"id": 1, "name": "Kepler-9b"},
                {"id": 2, "name": "Kepler-9c"},
                {"id": 3, "name": "Kepler-9d"}
            ],
            "discoverer": {"id": 1, "ref": "2013A&A...566A.126A"}
        }


## Exoplanets [/exoplanets]

### List Exoplanets [GET /exoplanets?page={n}]

+ Parameters
    + n (optional, integer, `1`) ... Page Number

+ Response 200 (application/json)

        {
            "num_results": 3, 
            "objects": [
                {
                    "id": 1, 
                    "name": "Kepler-9b",
                    "mass": 80.09, 
                    "radius": 9.438, 
                    "orbital_period": 1662336,
                    "year_discovered": 2010,
                    "star": {
                        "id": 1, 
                        "name": "Kepler-9", 
                        "constellation": {"id": 1, "abbrev":"Lyr"}
                    }, 
                    "discoverer": {"id": 1, "ref": "2013A&A...566A.126A"}
                },
                {
                    "id": 2, 
                    "name": "Kepler-9c",
                    "mass": 54.249, 
                    "radius": 9.225, 
                    "orbital_period": 3361824,
                    "year_discovered": 2010,
                    "star": {
                        "id": 1, 
                        "name": "Kepler-9", 
                        "constellation": {"id": 1, "abbrev":"Lyr"}
                    }, 
                    "discoverer": {"id": 1, "ref": "2013A&A...566A.126A"}
                },
                {
                    "id": 3, 
                    "name": "Kepler-9d",
                    "mass": null, 
                    "radius": 1.6, 
                    "orbital_period": 137376,
                    "year_discovered": 2010,
                    "star": {
                        "id": 1, 
                        "name": "Kepler-9", 
                        "constellation": {"id": 1, "abbrev":"Lyr"}
                    }, 
                    "discoverer": {"id": 1, "ref": "2013A&A...566A.126A"}
                }
            ], 
            "page": 1, 
            "total_pages": 1
        }

### Find Exoplanet [GET /exoplanets/{id}]

+ Parameters
    + id (required, integer, `2`) ... Exoplanet ID

+ Response 200 (application/json)

        {
            "id": 2, 
            "name": "Kepler-9c",
            "mass": 54.249, 
            "radius": 9.225, 
            "orbital_period": 3361824,
            "year_discovered": 2010,
            "star": {
                "id": 1, 
                "name": "Kepler-9", 
                "constellation": {"id": 1, "abbrev":"Lyr"}
            }, 
            "discoverer": {"id": 1, "ref": "2013A&A...566A.126A"}
        }


## Constellations [/constellations]

### List Constellations[GET /constellations?page={n}]

+ Parameters
    + n (optional, integer, `1`) ... Page Number

+ Response 200 (application/json)

        {
            "num_results": 2, 
            "objects": [
                {
                    "id": 1, 
                    "abbrev": "Lyr",
                    "name": "Lyra",
                    "family": "Hercules",
                    "meaning": "lyre / harp",
                    "area": 286,
                    "stars": [
                        {
                            "id": 1, 
                            "name": "Kepler-9", 
                            "exoplanets": [
                                {"id": 1, "name": "Kepler-9a"},
                                {"id": 2, "name": "Kepler-9b"},
                                {"id": 3, "name": "Kepler-9d"}
                            ]
                        }
                    ]
                },
                {
                    "id": 2, 
                    "abbrev": "Oct",
                    "name": "Octans",
                    "family": "La Caille",
                    "meaning": "octant (instrument)",
                    "area": 291,
                    "stars": [
                        {
                            "id": 2, 
                            "name": "HIP 64690", 
                            "exoplanets": []
                        }
                    ]
                }
            ], 
            "page": 1, 
            "total_pages": 1
        }

### Find Constellation [GET /constellations/{name}]

+ Parameters
    + name (required, integer, `1`) ... Constellation ID

+ Response 200 (application/json)

        {
            "id": 1, 
            "abbrev": "Lyr",
            "name": "Lyra",
            "family": "Hercules",
            "meaning": "lyre / harp",
            "area": 286,
            "stars": [
                {
                    "id": 1, 
                    "name": "Kepler-9", 
                    "exoplanets": [
                        {"id": 1, "name": "Kepler-9a"},
                        {"id": 2, "name": "Kepler-9b"},
                        {"id": 3, "name": "Kepler-9d"}
                    ]
                }
            ]
        }

## Publications [/publications]

### List Publications [GET /publications?page={n}]

+ Parameters
    + n (optional, integer, `1`) ... Page Number

+ Response 200 (application/json)

        {
            "num_results": 2, 
            "objects": [
                {
                    "id": 1, 
                    "ref": "2013A&A...566A.126A",
                    "title": "A dynamically-packed planetary system around GJ 667C with three super-Earths in its habitable zone",
                    "authors": "Anglada-Escudé, Guillem; Tuomi, Mikko; Gerlach, Enrico; Barnes, Rory",
                    "year":2013,
                    "journal": "Astronomy & Astrophysics",
                    "abstract": "Context. Since low-mass stars have low luminosities, orbits...",
                    "stars": [
                        {"id": 1, "name": "Kepler-9"}
                    ],
                    "exoplanets": [
                        {"id": 1, "name": "Kepler-9b"},
                        {"id": 2, "name": "Kepler-9c"},
                        {"id": 3, "name": "Kepler-9d"}
                    ]
                },
                {
                    "id": 2, 
                    "ref": "2011A&A...534A..58P",
                    "title": "The HARPS search for Earth-like planets in the habitable zone. I. Very low-mass planets around HD 20794, HD 85512, and HD 192310",
                    "authors": "Pepe, F.; Lovis, C.; Ségransan, D.; Benz, W.; Bouchy, F.; Dumusque, X.; Mayor, M.; Queloz, D.; Santos, N. C.; Udry, S.",
                    "year":2011,
                    "journal": "Astronomy & Astrophysics",
                    "abstract": "Context. In 2009 we started an intense radial-velocity monitoring of a few nearby, slowly-rotating...",
                    "stars": [
                        {"id": 2, "name": "HIP 64690"}
                    ],
                    "exoplanets": []
                }
            ], 
            "page": 1, 
            "total_pages": 1
        }

### Find Publication [GET /publications/{ref}]

+ Parameters
    + ref (required, integer, `1`) ... Publication ID

+ Response 200 (application/json)


        {
            "id": 1, 
            "ref": "2013A&A...566A.126A",
            "title": "A dynamically-packed planetary system around GJ 667C with three super-Earths in its habitable zone",
            "authors": "Anglada-Escudé, Guillem; Tuomi, Mikko; Gerlach, Enrico; Barnes, Rory",
            "journal": "Astronomy & Astrophysics",
            "year":2013,
            "abstract": "Context. Since low-mass stars have low luminosities, orbits...",
            "stars": [
                {"id": 1, "name": "Kepler-9"}
            ],
            "exoplanets": [
                {"id": 1, "name": "Kepler-9b"},
                {"id": 2, "name": "Kepler-9c"},
                {"id": 3, "name": "Kepler-9d"}
            ]
        }
        
## Search [/search]

### Search [GET /search/?q={query}&page={n}&mode={mode}]
+ Parameters
    + n (optional, integer, `1`) ... Page Number
    + query (required, string, `kepler`) ... Search Term
    + mode (required, string, `and`) ... Search mode, AND or OR
    
+ Response 200 (application/json)


        {
            "page" : 1,
            "total_pages" : 1,
            "num_results": 1000,
            "results" : [
                {"model" : "stars", "id": 1},
                {"model" : "stars", "id": 2},
                {"model" : "constellations", "id": 5}
            ]
        }